# Generated by Django 3.2.8 on 2021-10-15 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMedicalApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='desciption',
            new_name='description',
        ),
    ]
